language: python
dist: xenial
python:
- 2.7
- 3.6
- 3.7
install: pip install tox-travis
script: tox
after_success: 
cache:
  pip: true
notifications:
  webhooks:
    secure: xQWx86nm1BD7ZmIrR5PUS+QDcqYya8OctOOZRNBZW/YR/FBi5K1Sb6pim5kNPxReaovxOPWmAsQ1TN+ROzwphuvjp4EsgikzRXa00knTtMMGLwEdVnRVa/iRpLakknsdK2jyWEvLpE8OF+87070u/sZlOguxaXETYVBUwttMozbOrRVCsWohyUCLA+7tLWG+SnVvbsxctpcWyInN+KiyV0aHm4ipqeZoX3FR95fsB6ZJNxUU5+vP5LkaM17ezYNEOiEtQ9CtWKdo22s3bN3YxS7P5Fysv5LzP73UNnpDdhMgRuX3DhPG7bjf9Somybmg2OgwzdWxa2bylixY3vpetQU/PgZ2aHznDXtZpvXrOmXV5gHJvYh2kM9Dai8c7xTi+5o+ocWEzHrPJpvmNO8uqgq8TlNjg0PnDbGDmghIDciOD9dapWIGoOhSl03/kvryZ5wS46+Vwn2WULJEFTiVrBZgERHJv2J0etOCQh7BIJR4yb+IURnmZfjE5nfH++PEdgXbuANcEz+6sn8gI3oaPb14uo8rVUoYjwvl2Tczs9rp3VLqd34mE2Bo7lcofklCE9CuFTMXhb9ZHv63CtxjLUX7VjP1E8A9NarAyMYS1ROVLvyGcGGlVt1lios/PHsVWi3fiqTMEfAklgokswf6m0MK/jgRBmoRzOTkam0Mku4=
